repos:
  - name: markupsafe
    url: https://github.com/pallets/markupsafe
    label_allowlist:
      - bug
      - duplicate
    owner_map:
      "src/markupsafe/": "@pallets"
    indexed_sha: null

  - name: flask
    url: https://github.com/pallets/flask
    label_allowlist:
      - bug
      - needs clarification
      - duplicate
    owner_map:
      "src/flask/": "@pallets"
    indexed_sha: null

  - name: fastapi
    url: https://github.com/fastapi/fastapi
    label_allowlist:
      - bug
      - feature
      - duplicate
    owner_map:
      "fastapi/": "@tiangolo"
    indexed_sha: null